### PR TITLE
mason-js port

### PR DESCRIPTION
**Pull request by millzpaugh**
Move to mason-js instead of mason bash!

### CODE REVIEW

**Comment by springmeyer** [comment]
Looking really really good @millzpaugh - so excited this came together so nicely. Per the clang-tidy error I'm working on fixing this over at #68.

**Comment by springmeyer** [comment]
Let's hold on this until https://github.com/mapbox/node-cpp-skel/pull/111 is merged (and then use that as a guide land this - since we ended up with more changes in https://github.com/mapbox/node-cpp-skel/pull/111). Assigning to myself here for next actions.

**Comment by springmeyer** [comment]
> Let's hold on this until mapbox/node-cpp-skel#111 is merged (and then use that as a guide land this - since we ended up with more changes in mapbox/node-cpp-skel#111). Assigning to myself here for next actions.

Nevermind. I think mapbox/node-cpp-skel#111 is going to take a little more time and there is value to testing this next. So, next action is to have @millzpaugh take this branch for a spin and:

 - [ ] pair with @mapsam to try publishing a dev build from this branch
 - [ ] pair with @mapsam ensure that binary works downstream (and that `mason-js` is not invoked for "from binary" install, so there should be no `mason_packages` placed on the system in that scenario)

**Comment by millzpaugh** [comment]
# node-pre-gyp debugging
When running `make` in this vtquery branch, @mapsam and I encountered an error in `node-pre-gyp`. (see below) This is a blocker to publishing a binary of this branch to test in mapbox-maps. 

    V=1 ./node_modules/.bin/node-pre-gyp configure build --error_on_warnings=true --loglevel=error
    node-pre-gyp ERR! configure error 
    node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp configure --error_on_warnings=true --loglevel=error --module=/Users/annmillspaugh/mapbox/vtquery/lib/binding/vtquery.node --module_name=vtquery --module_path=/Users/annmillspaugh/mapbox/vtquery/lib/binding --node_abi_napi=node-v48' (Error: spawn node-gyp ENOENT)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/annmillspaugh/mapbox/vtquery/node_modules/node-pre-gyp/lib/util/compile.js:77:29)
    node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:188:7)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:202:12)
    node-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:348:16)
    node-pre-gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
    node-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:98:9)
    node-pre-gyp ERR! stack     at Function.Module.runMain (module.js:577:11)
    node-pre-gyp ERR! stack     at startup (node.js:159:18)
    node-pre-gyp ERR! stack     at node.js:444:3
    node-pre-gyp ERR! System Darwin 16.5.0
    node-pre-gyp ERR! command "/Users/annmillspaugh/.nvm/versions/node/v6.0.0/bin/node" "/Users/annmillspaugh/mapbox/vtquery/node_modules/.bin/node-pre-gyp" "configure" "build" "--error_on_warnings=true" "--loglevel=error"
    node-pre-gyp ERR! cwd /Users/annmillspaugh/mapbox/vtquery
    node-pre-gyp ERR! node -v v6.0.0
    node-pre-gyp ERR! node-pre-gyp -v v0.9.0
    node-pre-gyp ERR! not ok 
    Failed to execute 'node-gyp configure --error_on_warnings=true --loglevel=error --module=/Users/annmillspaugh/mapbox/vtquery/lib/binding/vtquery.node --module_name=vtquery --module_path=/Users/annmillspaugh/mapbox/vtquery/lib/binding --node_abi_napi=node-v48' (Error: spawn node-gyp ENOENT)
    make: *** [release] Error 1

Initially we thought it was a versioning error re: https://github.com/mapbox/node-pre-gyp/blob/master/lib/util/versioning.js#L288, but then realized that our dev version for the package was invalid semver, i.e. `0.2.0alpha` vs `0.2.0-alpha` and was being parsed incorrectly.

@springmeyer any insight would be 👍 !

**Comment by springmeyer** [comment]
@millzpaugh thanks for this ticket. That is an odd error. The most telling part of the error is:

> (Error: spawn node-gyp ENOENT)

Which means that node attempted to call `node-gyp` and the `ENOENT` means it was not found. So, `node-pre-gyp` fell back to a source compile (since no pre-published vtquery binary was available) and a source compile needs to call `node-gyp` and `node-gyp` was not available on the PATH. This is not something that should happen because `node-gyp` is bundled inside a node install (and [node-pre-gyp does some backflips to find it](https://github.com/mapbox/node-pre-gyp/blob/master/lib/util/compile.js#L11-L18). So it seems like `node-pre-gyp` failed to find `node-gyp` in all the likely places and had to fall back to just calling it without using a specific path and just hoping it was there per ([so this line was hit](https://github.com/mapbox/node-pre-gyp/blob/cf559670e6a59768437bd35229cdd06988e4748e/lib/util/compile.js#L69)). And that failed.

So, overall this seems to indicate something wrong with your nodejs install. I notice your node install is `/Users/annmillspaugh/.nvm/versions/node/v6.0.0/bin/node`. Node v6.0.0 was released ~ 2 years ago (https://nodejs.org/en/blog/release/v6.0.0/). So, maybe try upgrading to the latest node v6 version (v6.14.0) and see if the problem persists?

**Comment by mapsam** [comment]
Good eye @springmeyer. Sorry I didn't think about that @millzpaugh! Can confirm `make` works locally for me with the following versions:

* node: v6.11.1
* npm: 5.6.0

AND 

* node: v4.8.4
* npm: 2.15.11

**Review by mapsam — APPROVED** [review]
@millzpaugh @springmeyer I just updated with master and things are looking 👍 - feel free to merge this in whenever you are ready!

**Comment by springmeyer** [comment]
Thanks for rebasing @mapsam!  I recall there were a few changes in node-cop-skel that we landed after working on this branch so before merging we’ll want to do a quick diff of the key build files to ensure this is using the latest skel patterns exactly.

**Comment by mapsam** [comment]
@springmeyer good point - let me know if you'd like me to look through that or if you/@millzpaugh plan on taking care of it!

**Comment by springmeyer** [comment]
@mapsam I'm inclined to pause on this and come up with a plan for porting all our modules to mason-js, and hitting this then. So, I'm going to close this for now.

**Comment by mapsam** [comment]
👍 good call - thanks for closing!

**Pull request closed without merging**
